### ISSUE TITLE
Error with newer versions of python

### ISSUE THREAD

**Issue by dvoc** [Mickaelh51/rsi-alarm-gateway#1]
Hello,
Great work but seems that is not compatible with newer versions of python (3.8). I've tested with 3.5 and it works.
You have to edit Dockerfile_rpi in indicating 
FROM arm32v7/python:3.5-alpine

Also username and password has to be set-up in order to work with mosquitto mqtt server:
in mqtt.py you have to add:

client.username_pw_set(username="user",password="passwd")

Rgds

**Comment by Mickaelh51** [comment]
Hi, I added username and password feature
and fixed dockerfile for RPI (can you test please in RPI ?)
thanks in advance
