### ISSUE TITLE
Stability

### ISSUE THREAD

**Issue by dvoc** [Mickaelh51/rsi-alarm-gateway#2]
After several hours working the gateway is not stable enough, this is the error log:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 95, in client_thread
    if (client_auth(connection)):
  File "/usr/src/app/utils.py", line 39, in client_auth
    alarm_challenge = challenge_and_key.decode().split(',')[2]
IndexError: list index out of range

I've declared all elements and zones of my system (I've four zones) in config.json.

**Comment by Mickaelh51** [comment]
Hi,
Can you send me a trace (with tcpdump) between your alarm and server ?
1 trace at alarm startup
1 trace with server crash
What is your alarm version ?

Have a good day

**Comment by dvoc** [comment]
Hello,
My alarm version is 08.13.26.03859C. Now the server is crashing with arm/disarm from remote control. I attach tcpdump doing that operation.

[capture2.zip](https://github.com/Mickaelh51/rsi-alarm-gateway/files/4926499/capture2.zip)

Many thanks

**Comment by Mickaelh51** [comment]
I'm sorry for my late answer.
is it ok for you ?

**Comment by Mickaelh51** [comment]
I can't troubleshoot with this capture, it's too small..

`alarm_challenge = challenge_and_key.decode().split(',')[2]` issue
it's when your alarm try to authentificate to gateway

**Comment by Mickaelh51** [comment]
I, it's the same isseu that : https://github.com/Mickaelh51/rsi-alarm-gateway/issues/8
you can test the last version built today.

have a good day
