### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by moodyblue** [Mickaelh51/rsi-alarm-gateway#4]
I have an alarm system supplied by Prosegur. The alarm panel is a WIP210. I would like to know technical details of the WIP210, namely:

1) Can the WIP210 send signals both through IP and GPRS ? I want to retain the remote monitoring of my house and this requires GPRS, but I also want to use sensor status for IoT purposes
2) The WIP210 communicates alarms only ? Or can it also communicate a movement detection when alarm panel is not armed ?
3) I see that your code was developed for MQTT with HA. I'm using MQTT with OpenHAB. Would that be a problem ?

Currently my WIP210 is not connected to IP but I have a RJ45 socket 1 meter away, so I'm considering to ask Prosegur to come here and connect the panel to my IP installation.

Thanks

**Comment by Mickaelh51** [comment]
Hi,
My answers below

Le lun. 4 janv. 2021 à 16:25, moodyblue <notifications@github.com> a écrit :

> I have an alarm system supplied by Prosegur. The alarm panel is a WIP210.
> I would like to know technical details of the WIP210, namely:
>
>    1. Can the WIP210 send signals both through IP and GPRS ? I want to
>    retain the remote monitoring of my house and this requires GPRS, but I also
>    want to use sensor status for IoT purposes
>
> I'm not sure, but for me it's possible to connect GPRS + RJ45

>
>    1. The WIP210 communicates alarms only ? Or can it also communicate a
>    movement detection when alarm panel is not armed ?
>
> When alarm is not armed, there is not signal send to the gateway (only a
sort of ping once a day)

>
>    1. I see that your code was developed for MQTT with HA. I'm using MQTT
>    with OpenHAB. Would that be a problem ?
>
> It's possible to use other Home Automation system.
With HA you have the auto discovery. But with openhab you can configure
MQTT devices for each gateway sensors.

>
>
> Currently my WIP210 is not connected to IP but I have a RJ45 socket 1
> meter away, so I'm considering to ask Prosegur to come here and connect the
> panel to my IP installation.
>

Yes, good idea. But I don't know if Prosegur wants to configure your
central with other IP than them servers.
My advice, juste ask to Procegur if it's possible to have GPRS and RJ45,
and you configure rsi gateway's IP in central's configuration.

++

**Comment by moodyblue** [comment]
Thanks a lot for your answers. 

`When alarm is not armed, there is not signal send to the gateway (only a sort of ping once a day)` -> this rules out my main intention to use it for IoT. I wanted to use movement sensors to switch on lights or heating when alarm is not armed.

But I also want to use it to block the garage door when the alarm is armed, so `Can the WIP210 send signals both through IP and GPRS` is also important to me.

**Comment by Mickaelh51** [comment]
Le lun. 4 janv. 2021 à 17:12, moodyblue <notifications@github.com> a écrit :

> Thanks a lot for your answers.
>
> When alarm is not armed, there is not signal send to the gateway (only a
> sort of ping once a day) -> this rules out my main intention to use it
> for IoT. I wanted to use movement sensors to switch on lights or heating
> when alarm is not armed.
>
Yes, I also think that, but it's not possible


> But I also want to use it to block the garage door when the alarm is
> armed, so Can the WIP210 send signals both through IP and GPRS is also
> important to me.
>
if it's possible to send both, It will be OK

++

**Comment by moodyblue** [comment]
Thanks
