### ISSUE TITLE
Need basic info

### ISSUE THREAD

**Issue by kervoaz** [Mickaelh51/rsi-alarm-gateway#5]
Hello,

I try to capture data sent by the system. I have done a basic http server and setup the alarm to push info on my server. I don't receive any data(My server is ok from another computer from my network). 
According your code, the server is a basic HTTP server listen on 888, rigth?
Do you have any clue/tips  I can check to receive info?

Merci

**Comment by kervoaz** [comment]
hum ... it is a TCP server, sorry...

**Comment by Mickaelh51** [comment]
Hi
exactly it's a TCP server.
RSI sends a "ping" each day, but just one
Otherwise, you can open the keypad or siren to put them on auto protection.

have a good day
