### ISSUE TITLE
NOKEY error

### ISSUE THREAD

**Issue by longzheng** [Mickaelh51/rsi-alarm-gateway#8]
I tried using this on a Videofied XT-iP 730 panel with firmware 04.04.37.0F8F but I ran into an error with

![panel](https://github.com/Mickaelh51/rsi-alarm-gateway/assets/484912/034dca51-9a92-4d89-be9a-7463527d07bf)

```
2023-05-28 15:07:22 Exception in thread Thread-2:
2023-05-28 15:07:22 Traceback (most recent call last):
2023-05-28 15:07:22   File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
2023-05-28 15:07:22     self.run()
2023-05-28 15:07:22   File "/usr/local/lib/python3.7/threading.py", line 870, in run
2023-05-28 15:07:22     self._target(*self._args, **self._kwargs)
2023-05-28 15:07:22   File "server.py", line 95, in client_thread
2023-05-28 15:07:22     if (client_auth(connection)):
2023-05-28 15:07:22   File "/usr/src/app/utils.py", line 40, in client_auth
2023-05-28 15:07:22     alarm_challenge = challenge_and_key.decode().split(',')[2]
2023-05-28 15:07:22 IndexError: list index out of range
```

I added some additional logging on the response and I can see my request/responses are

```
IDENT,1000\x1a
IDENT,FD304015210A0241,2\x1a
VERSION,2,0\x1a
AUTH1,FB6223073E5A09E0DF9E81F7A3C832FC\x1a
NOKEY\x1a
```

The panel response to AUTH1 seems to be an error. I suspect it's because this panel's firmware has fixed the vulnerability documented in https://cybergibbons.com/alarms-2/multiple-serious-vulnerabilities-in-rsi-videofieds-alarm-protocol/

I'm assuming you haven't come across this before but I thought I might just document this just in case anyone else comes across a similar error.

**Comment by Mickaelh51** [comment]
Hi,
thanks for your message.
I'm not sure about this issue.
When I red cybergibbons doc

> RSI Videofied have stated to CERT/CC that this is fixed in version 3 of their protocol which is currently being rolled out.

But in your trace, I can see `VERSION,2,0\x1a`

**Comment by longzheng** [comment]
@Mickaelh51 which model of the panel do you have?

Do you happen to have a copy of the Frontel server? I've been trying to get a copy to inspect how the panel and the server would connect, but all the download links are dead on https://resideo.kayako.com/article/657-frontel-software-download-latest

**Comment by longzheng** [comment]
I figured out the problem.

I got a copy of the Frontel server software which comes with a simulator. I used Wireshark to sniff the TCP traffic between that and the server.

```
IDENT,1000.

IDENT,E030000013080001,2.

SETKEY,00180000100010030001000010018800.VERSION,2,0.AUTH1,FDE9C39668661E941B0B5072E3CE6AC0.

AUTH2,1B48A26BE93ECD4A712FB42A69056080,0123456789ABCDEF0123456789ABCDEF.

AUTH3,F4D8B76294AB52F2F24AC72788F428A8.

AUTH_SUCCESS,12345678,
```

It turns out there needs to be a `SETKEY` request from the server to the panel.  I re-read the documentation at https://cybergibbons.com/alarms-2/multiple-serious-vulnerabilities-in-rsi-videofieds-alarm-protocol/ and it also makes mention of the `SETKEY` command. It seems like it is required the first time the panel connects to a server and my panel has never connected to a server before so maybe it needs to be set at least once.

I modified your code to
```
      if (serial and key): 
        msg = 'SETKEY,' + key + '\x1a'
        conn.send(msg.encode())
        if(conn.send(b"VERSION,2,0\x1a")):
```
and it now connects. 

```
2023-06-01 20:38:43 [2023-06-01 10:38:43,214] - utils - INFO - Answer: AUTH_SUCCESS,0000,2,20220602203838,5,2,E2632323110,0,XLP040402,0,07FF
2023-06-01 20:38:43 [2023-06-01 10:38:43,214] - utils - INFO - Logging successful !!
```

I'm not very familiar with Python so I'll do a bit more debugging and testing and I'll open a PR with this change.

**Comment by Mickaelh51** [comment]
Very good job @longzheng !
thanks a lot.
I look forward your PR ;)

have a good day

**Comment by longzheng** [comment]
Sorry I've been distracted by Diablo 4 so haven't made the PR yet.

Also I found documentation for all the events in the system, not sure if it helps you.

[EN_-_FRONTEL_-_EVENTS_LIST_-_NOTE.pdf](https://github.com/Mickaelh51/rsi-alarm-gateway/files/11658341/EN_-_FRONTEL_-_EVENTS_LIST_-_NOTE.pdf)
